// GENERATED by tools/preprocess_assets.py - do not edit
// Real fruit art keyed by fruit type id; fruits absent here keep
// their procedural OT.S painter (see js/assets.js).
window.OT = window.OT || {};
OT.AM = {
 "apple": {
  "src": "assets/img/Apple.png",
  "w": 204,
  "h": 256
 },
 "banana": {
  "src": "assets/img/Banana.png",
  "w": 251,
  "h": 256
 },
 "cherry": {
  "src": "assets/img/Cherry.png",
  "w": 252,
  "h": 256
 },
 "grape": {
  "src": "assets/img/Grape.png",
  "w": 233,
  "h": 256
 },
 "lemon": {
  "src": "assets/img/Lemon.png",
  "w": 256,
  "h": 249
 },
 "orange": {
  "src": "assets/img/Orange.png",
  "w": 224,
  "h": 256
 },
 "pineapple": {
  "src": "assets/img/Pineapple.png",
  "w": 164,
  "h": 256
 },
 "pomegranate": {
  "src": "assets/img/Pomegranate.png",
  "w": 230,
  "h": 256
 },
 "strawberry": {
  "src": "assets/img/Strawberry.png",
  "w": 201,
  "h": 256
 },
 "watermelon": {
  "src": "assets/img/Watermelon.png",
  "w": 214,
  "h": 256
 }
};
