// GENERATED by tools/preprocess_assets.py - do not edit
// Real fruit art keyed by fruit type id; fruits absent here keep
// their procedural OT.S painter (see js/assets.js).
window.OT = window.OT || {};
OT.AM = {
 "apple": {
  "src": "assets/img/Apple.png",
  "w": 204,
  "h": 256
 },
 "banana": {
  "src": "assets/img/Banana.png",
  "w": 251,
  "h": 256
 },
 "cherry": {
  "src": "assets/img/Cherry.png",
  "w": 252,
  "h": 256
 },
 "pineapple": {
  "src": "assets/img/Pineapple.png",
  "w": 164,
  "h": 256
 },
 "strawberry": {
  "src": "assets/img/Strawberry.png",
  "w": 201,
  "h": 256
 }
};
