// GENERATED by tools/preprocess_assets.py - do not edit
// OT.AM: real fruit art keyed by fruit type id.
// OT.AM_SPROUT: real Sprout art keyed by growth stage then mood.
// Anything absent from either map keeps its procedural OT.S painter
// (see js/assets.js); Sprout delegates per stage+mood, not all-or-nothing.
window.OT = window.OT || {};
OT.AM = {
 "apple": {
  "src": "assets/img/Apple.png",
  "w": 204,
  "h": 256
 },
 "banana": {
  "src": "assets/img/Banana.png",
  "w": 251,
  "h": 256
 },
 "cherry": {
  "src": "assets/img/Cherry.png",
  "w": 252,
  "h": 256
 },
 "grape": {
  "src": "assets/img/Grape.png",
  "w": 233,
  "h": 256
 },
 "lemon": {
  "src": "assets/img/Lemon.png",
  "w": 256,
  "h": 249
 },
 "orange": {
  "src": "assets/img/Orange.png",
  "w": 224,
  "h": 256
 },
 "pineapple": {
  "src": "assets/img/Pineapple.png",
  "w": 164,
  "h": 256
 },
 "pomegranate": {
  "src": "assets/img/Pomegranate.png",
  "w": 230,
  "h": 256
 },
 "strawberry": {
  "src": "assets/img/Strawberry.png",
  "w": 201,
  "h": 256
 },
 "watermelon": {
  "src": "assets/img/Watermelon.png",
  "w": 214,
  "h": 256
 }
};
OT.AM_SPROUT = {
 "3": {
  "aim": {
   "src": "assets/img/Sprout_Stage3_Aim.png",
   "w": 413,
   "h": 512
  },
  "cheer": {
   "src": "assets/img/Sprout_Stage3_Cheer.png",
   "w": 307,
   "h": 512
  },
  "idle": {
   "src": "assets/img/Sprout_Stage3_Idle.png",
   "w": 296,
   "h": 512
  },
  "sad": {
   "src": "assets/img/Sprout_Stage3_Sad.png",
   "w": 320,
   "h": 512
  }
 }
};
